from __future__ import annotations

TEAMS = {
    "1": {
        "name": "Atlanta Hawks",
        "abbrev": "ATL",
        "primary_color": "#E03A3E",
        "secondary_color": "#C1D32F",
        "logo": "https://a.espncdn.com/i/teamlogos/nba/500/atl.png",
        "conference": "East",
        "division": "Southeast",
    },
    "2": {
        "name": "Boston Celtics",
        "abbrev": "BOS",
        "primary_color": "#007A33",
        "secondary_color": "#BA9653",
        "logo": "https://a.espncdn.com/i/teamlogos/nba/500/bos.png",
        "conference": "East",
        "division": "Atlantic",
    },
    "4": {
        "name": "Brooklyn Nets",
        "abbrev": "BKN",
        "primary_color": "#000000",
        "secondary_color": "#FFFFFF",
        "logo": "https://a.espncdn.com/i/teamlogos/nba/500/bkn.png",
        "conference": "East",
        "division": "Atlantic",
    },
    "5": {
        "name": "Charlotte Hornets",
        "abbrev": "CHA",
        "primary_color": "#1D1160",
        "secondary_color": "#00788C",
        "logo": "https://a.espncdn.com/i/teamlogos/nba/500/cha.png",
        "conference": "East",
        "division": "Southeast",
    },
    "6": {
        "name": "Chicago Bulls",
        "abbrev": "CHI",
        "primary_color": "#CE1141",
        "secondary_color": "#000000",
        "logo": "https://a.espncdn.com/i/teamlogos/nba/500/chi.png",
        "conference": "East",
        "division": "Central",
    },
    "7": {
        "name": "Cleveland Cavaliers",
        "abbrev": "CLE",
        "primary_color": "#860038",
        "secondary_color": "#041E42",
        "logo": "https://a.espncdn.com/i/teamlogos/nba/500/cle.png",
        "conference": "East",
        "division": "Central",
    },
    "8": {
        "name": "Dallas Mavericks",
        "abbrev": "DAL",
        "primary_color": "#00538C",
        "secondary_color": "#002B5E",
        "logo": "https://a.espncdn.com/i/teamlogos/nba/500/dal.png",
        "conference": "West",
        "division": "Southwest",
    },
    "9": {
        "name": "Denver Nuggets",
        "abbrev": "DEN",
        "primary_color": "#0E2240",
        "secondary_color": "#FEC524",
        "logo": "https://a.espncdn.com/i/teamlogos/nba/500/den.png",
        "conference": "West",
        "division": "Northwest",
    },
    "10": {
        "name": "Detroit Pistons",
        "abbrev": "DET",
        "primary_color": "#C8102E",
        "secondary_color": "#1D42BA",
        "logo": "https://a.espncdn.com/i/teamlogos/nba/500/det.png",
        "conference": "East",
        "division": "Central",
    },
    "11": {
        "name": "Golden State Warriors",
        "abbrev": "GSW",
        "primary_color": "#1D428A",
        "secondary_color": "#FFC72C",
        "logo": "https://a.espncdn.com/i/teamlogos/nba/500/gs.png",
        "conference": "West",
        "division": "Pacific",
    },
    "14": {
        "name": "Houston Rockets",
        "abbrev": "HOU",
        "primary_color": "#CE1141",
        "secondary_color": "#000000",
        "logo": "https://a.espncdn.com/i/teamlogos/nba/500/hou.png",
        "conference": "West",
        "division": "Southwest",
    },
    "15": {
        "name": "Indiana Pacers",
        "abbrev": "IND",
        "primary_color": "#002D62",
        "secondary_color": "#FDBB30",
        "logo": "https://a.espncdn.com/i/teamlogos/nba/500/ind.png",
        "conference": "East",
        "division": "Central",
    },
    "16": {
        "name": "LA Clippers",
        "abbrev": "LAC",
        "primary_color": "#C8102E",
        "secondary_color": "#1D428A",
        "logo": "https://a.espncdn.com/i/teamlogos/nba/500/lac.png",
        "conference": "West",
        "division": "Pacific",
    },
    "17": {
        "name": "Los Angeles Lakers",
        "abbrev": "LAL",
        "primary_color": "#552583",
        "secondary_color": "#FDB927",
        "logo": "https://a.espncdn.com/i/teamlogos/nba/500/lal.png",
        "conference": "West",
        "division": "Pacific",
    },
    "19": {
        "name": "Memphis Grizzlies",
        "abbrev": "MEM",
        "primary_color": "#5D76A9",
        "secondary_color": "#12173F",
        "logo": "https://a.espncdn.com/i/teamlogos/nba/500/mem.png",
        "conference": "West",
        "division": "Southwest",
    },
    "20": {
        "name": "Miami Heat",
        "abbrev": "MIA",
        "primary_color": "#98002E",
        "secondary_color": "#F9A01B",
        "logo": "https://a.espncdn.com/i/teamlogos/nba/500/mia.png",
        "conference": "East",
        "division": "Southeast",
    },
    "21": {
        "name": "Milwaukee Bucks",
        "abbrev": "MIL",
        "primary_color": "#00471B",
        "secondary_color": "#EEE1C6",
        "logo": "https://a.espncdn.com/i/teamlogos/nba/500/mil.png",
        "conference": "East",
        "division": "Central",
    },
    "22": {
        "name": "Minnesota Timberwolves",
        "abbrev": "MIN",
        "primary_color": "#0C2340",
        "secondary_color": "#236192",
        "logo": "https://a.espncdn.com/i/teamlogos/nba/500/min.png",
        "conference": "West",
        "division": "Northwest",
    },
    "23": {
        "name": "New Orleans Pelicans",
        "abbrev": "NOP",
        "primary_color": "#0C2340",
        "secondary_color": "#C8102E",
        "logo": "https://a.espncdn.com/i/teamlogos/nba/500/no.png",
        "conference": "West",
        "division": "Southwest",
    },
    "24": {
        "name": "New York Knicks",
        "abbrev": "NYK",
        "primary_color": "#006BB6",
        "secondary_color": "#F58426",
        "logo": "https://a.espncdn.com/i/teamlogos/nba/500/ny.png",
        "conference": "East",
        "division": "Atlantic",
    },
    "25": {
        "name": "Oklahoma City Thunder",
        "abbrev": "OKC",
        "primary_color": "#007AC1",
        "secondary_color": "#EF3B24",
        "logo": "https://a.espncdn.com/i/teamlogos/nba/500/okc.png",
        "conference": "West",
        "division": "Northwest",
    },
    "26": {
        "name": "Orlando Magic",
        "abbrev": "ORL",
        "primary_color": "#0077C0",
        "secondary_color": "#C4CED4",
        "logo": "https://a.espncdn.com/i/teamlogos/nba/500/orl.png",
        "conference": "East",
        "division": "Southeast",
    },
    "27": {
        "name": "Philadelphia 76ers",
        "abbrev": "PHI",
        "primary_color": "#006BB6",
        "secondary_color": "#ED174C",
        "logo": "https://a.espncdn.com/i/teamlogos/nba/500/phi.png",
        "conference": "East",
        "division": "Atlantic",
    },
    "28": {
        "name": "Phoenix Suns",
        "abbrev": "PHX",
        "primary_color": "#1D1160",
        "secondary_color": "#E56020",
        "logo": "https://a.espncdn.com/i/teamlogos/nba/500/phx.png",
        "conference": "West",
        "division": "Pacific",
    },
    "29": {
        "name": "Portland Trail Blazers",
        "abbrev": "POR",
        "primary_color": "#E03A3E",
        "secondary_color": "#000000",
        "logo": "https://a.espncdn.com/i/teamlogos/nba/500/por.png",
        "conference": "West",
        "division": "Northwest",
    },
    "30": {
        "name": "Sacramento Kings",
        "abbrev": "SAC",
        "primary_color": "#5A2D81",
        "secondary_color": "#63727A",
        "logo": "https://a.espncdn.com/i/teamlogos/nba/500/sac.png",
        "conference": "West",
        "division": "Pacific",
    },
    "31": {
        "name": "San Antonio Spurs",
        "abbrev": "SAS",
        "primary_color": "#000000",
        "secondary_color": "#C4CED4",
        "logo": "https://a.espncdn.com/i/teamlogos/nba/500/sa.png",
        "conference": "West",
        "division": "Southwest",
    },
    "38": {
        "name": "Toronto Raptors",
        "abbrev": "TOR",
        "primary_color": "#CE1141",
        "secondary_color": "#000000",
        "logo": "https://a.espncdn.com/i/teamlogos/nba/500/tor.png",
        "conference": "East",
        "division": "Atlantic",
    },
    "40": {
        "name": "Utah Jazz",
        "abbrev": "UTA",
        "primary_color": "#002B5C",
        "secondary_color": "#F9A01B",
        "logo": "https://a.espncdn.com/i/teamlogos/nba/500/utah.png",
        "conference": "West",
        "division": "Northwest",
    },
    "41": {
        "name": "Washington Wizards",
        "abbrev": "WAS",
        "primary_color": "#002B5C",
        "secondary_color": "#E31837",
        "logo": "https://a.espncdn.com/i/teamlogos/nba/500/wsh.png",
        "conference": "East",
        "division": "Southeast",
    },
}
